"""add order_id to deployable_tasks

Revision ID: 0c3daa07ad21
Revises: 5a58bad794b2
Create Date: 2026-07-28 17:56:45.675780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3daa07ad21'
down_revision: Union[str, Sequence[str], None] = '5a58bad794b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_deployable_tasks_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployable_tasks_order_id'))
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
