"""add mes test/live urls to clients

Revision ID: 21c2ab2f57f2
Revises: e1f2a3b4c5d6
Create Date: 2026-09-03 15:27:31.103320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c2ab2f57f2'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mes_test_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('mes_live_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('mes_live_url')
        batch_op.drop_column('mes_test_url')

    # ### end Alembic commands ###
