"""add deployable_tasks table

Revision ID: 5a58bad794b2
Revises: f0e04321533d
Create Date: 2026-07-28 17:40:08.862359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a58bad794b2'
down_revision: Union[str, Sequence[str], None] = 'f0e04321533d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployable_tasks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('order_name', sa.String(length=500), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('item_custom_id', sa.String(length=255), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('target', sa.String(length=10), nullable=False),
    sa.Column('target_status', sa.String(length=50), nullable=False),
    sa.Column('gate_status', sa.String(length=50), nullable=True),
    sa.Column('assigned_developer_custom_id', sa.String(length=255), nullable=True),
    sa.Column('assigned_developer_name', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployable_tasks_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployable_tasks_task_id'))

    op.drop_table('deployable_tasks')
    # ### end Alembic commands ###
