"""add pos_id to deployable_tasks

Revision ID: ce1741d3e0de
Revises: 0c3daa07ad21
Create Date: 2026-07-29 12:06:58.231898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1741d3e0de'
down_revision: Union[str, Sequence[str], None] = '0c3daa07ad21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_id', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.drop_column('pos_id')

    # ### end Alembic commands ###
