"""drop gate_status and is_ready from deployable_tasks

Revision ID: daf5992b3642
Revises: ce1741d3e0de
Create Date: 2026-07-29 16:34:58.232682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf5992b3642'
down_revision: Union[str, Sequence[str], None] = 'ce1741d3e0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.drop_column('is_ready')
        batch_op.drop_column('gate_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployable_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gate_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_ready', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
